spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Riot?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: 20060304Aa.
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    generate-ddl: true
    hibernate:
      ddl-auto: update
  main:
    allow-circular-references: true

server:
  port: 9090
  servlet:
    encoding:
      charset: UTF-8
      force: true